### ISSUE TITLE
ADC command not generating carry bit

### ISSUE THREAD

**Issue by Java6502** [DylanSpeiser/Java-6502-Emulator#3]
Sir,
For some reason, the internal logic for your ADC method on the CPU is not converting from byte to short correctly.  The result is that the carry bit is not set correctly.  For a test run the following ASM

.org $8000

reset:
    clc                 ;Clear carry bit
    cld                 ;Clear decimal bit
    lda #$14            ;Load a Hex 14 into the accumulator.
    adc #$F0            ;Add the Hex F0 in the accumulator to Hex 14
    sta $0200           ;Store the result in memory location 0200.
    lda #$00            ;Note, the carry bit hasn't been cleared, so we can store
    adc #$00            ;it as follows.  The carry bit plus zero should store 01 in 
                        ;the accumulator, but then should set the carry bit to 0.
    sta $0201

loop:
    jmp loop

    .org $fffc
    .word reset
    .word $0000

The following seems to fix the issue.

//INSTRUCTIONS
	public void ADC() {
		fetch();
                System.out.println("Printing a: "+Utils.byteToHexString(a));
                System.out.println("Printing fetched: "+Utils.byteToHexString(fetched));
                System.out.println("Printing carry: "+(short)(getFlag('C') ? 1 : 0));
                short tempa = (short)Byte.toUnsignedInt(a);
                short tempFetch = (short)Byte.toUnsignedInt(fetched);
                short carry = (short)(getFlag('C')?1:0);
		//short temp = (short)((short)a + (short)fetched + (short)(getFlag('C') ? 1 : 0));
                short temp = (short)(tempa + tempFetch + carry);
                System.out.println("Printing temp: "+Short.toString(temp));
		setFlag('C', temp > 255);
		setFlag('Z', (temp & 0x00FF) == 0);
		setFlag('N', (temp & 0x80) == 0x80);
		setFlag('V', (~((short)a^(short)fetched) & ((short)a^(short)temp) & 0x0080)==0x0080);
		a = (byte)temp;
		additionalCycles++;
	}

**Comment by DylanSpeiser** [comment]
Fixed in v 1.4
