### ISSUE TITLE
Change ROM load address

### ISSUE THREAD

**Issue by raidersan** [DylanSpeiser/Java-6502-Emulator#8]
Adding an changeable address where the ROM should be loaded would a great addition

**Comment by DylanSpeiser** [comment]
Like in Ben's kit, the CPU always sees the ROM as $8000-$ffff. The bottom half of the address space is more configurable. When loading a .bin file, I would always load one that is the correct size for the ROM (32k). The files always get loaded at the beginning of the ROM, $8000.

**Comment by raidersan** [comment]
I was trying to replicate the C64 kernel ROM that needs to load @ E000. It contains the reset vectors that I wanted to simulate. I am busy playing with the code to see if I can make it load @ whatever ROM page is currently displayed. That would work for me. But then the BASIC ROM would have to follow in the RAM address space. I'll get something working and branch it out, you can always evaluate to see if it is valuable to the master or not.
